FROM rust:1-trixie
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    llvm \
    clang \
    clang-tools \
    pkg-config \
    build-essential  \
    protobuf-compiler \
    pkg-config \
    libproc2-dev \
    protobuf-compiler
    
RUN cargo install cargo-deb@3.6.3
# Copy our source and setup our working dir.
COPY . /tmp/build
WORKDIR /tmp/build

ENTRYPOINT [ "bash" ]
